test:
	@node -e "console.log('make test ok')"

build:
	@node -e "console.log('make build ok')"

alpha beta:
	@node -e "console.log('make multi-target ok')"

gamma::
	@node -e "console.log('make double-colon ok')"
